apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-proxy
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  accessPolicy:
    inbound:
      rules:
        - application: ia-key-metrics
          namespace: teamia
        - application: memu-data
          namespace: fugl-fonix
    outbound:
      external:
        - host: api.siteimprove.com
        - host: api.eu.siteimprove.com
        - host: siteimprove.com
        - host: raw.githubusercontent.com
        - host: analytics.eu.amplitude.com
  ingresses:
    - https://reops-proxy.intern.dev.nav.no
  liveness:
    path: /isAlive
    initialDelay: 20
  readiness:
    path: /isReady
    initialDelay: 20
  env:
    - name: SITEIMPROVE
      value: {{SITEIMPROVE}}
    - name: AMPLITUDE_100000009
      value: {{AMPLITUDE_100000009}}
    - name: AMPLITUDE_100000264
      value: {{AMPLITUDE_100000264}}
    - name: AMPLITUDE_100000243
      value: {{AMPLITUDE_100000243}}
    - name: AMPLITUDE_100000244
      value: {{AMPLITUDE_100000244}}
    - name: AMPLITUDE_100002286
      value: {{AMPLITUDE_100002286}}
    - name: AMPLITUDE_100003868
      value: {{AMPLITUDE_100003868}}
    - name: AMPLITUDE_100003867
      value: {{AMPLITUDE_100003867}}
    - name: AMPLITUDE_100002016
      value: {{AMPLITUDE_100002016}}
    - name: REOPS
      value: {{REOPS}}
