apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-proxy
  namespace: team-researchops
  labels:
    team: team-researchops
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://websta.ansatt.nav.no,https://webapps.ansatt.nav.no,https://webapps.nav.no,https://webapps.intern.nav.no,https://felgen.ansatt.nav.no,https://innblikk.ansatt.nav.no,https://startumami.ansatt.nav.no"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  image: {{ image }}
  port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    inbound:
      rules:
        - application: arbeidsgiver-datafortelling
          namespace: arbeidsgiver-data
        - application: memu-data
          namespace: fugl-fonix
        - application: reops-websta
          namespace: team-researchops
        - application: umami-start
          namespace: team-researchops
        - application: delta-frontend
          namespace: delta
        - application: reops-felgen
          namespace: team-researchops
        - application: reops-leak
          namespace: team-researchops
    outbound:
      external:
        - host: api.siteimprove.com
        - host: api.eu.siteimprove.com
        - host: siteimprove.com
        - host: nav.no
        - host: raw.githubusercontent.com
  ingresses:
    - https://reops-proxy.intern.nav.no
    - https://reops-proxy.ansatt.nav.no
  liveness:
    path: /isAlive
    initialDelay: 20
  readiness:
    path: /isReady
    initialDelay: 20
  env:
    - name: SITEIMPROVE
      value: {{SITEIMPROVE}}
    - name: REOPS
      value: {{REOPS}}