name: Deploy to gcp

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  build:
    name: Build and push docker conatainer
    runs-on: ubuntu-latest
    environment: production
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: 'Build and push'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: team-researchops
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    name: Deploy to dev-gcp
    needs: build
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - name: Generate nais variables
        run: |
          cat > .nais/dev-vars.yaml <<EOF
          SITEIMPROVE: ${{ secrets.SITEIMPROVE }}
          REOPS: ${{ secrets.REOPS }}
          EOF
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-gcp.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
          VARS: .nais/dev-vars.yaml

  deploy-prod:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    name: Deploy to prod-gcp
    needs: build
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - name: Generate nais variables
        run: |
          cat > .nais/prod-vars.yaml <<EOF
          SITEIMPROVE: ${{ secrets.SITEIMPROVE }}
          REOPS: ${{ secrets.REOPS }}
          EOF
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod-gcp.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
          VARS: .nais/prod-vars.yaml
      - name: "Create deployment tag"
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TAG_NAME="prod-$(date -u +'%Y.%m.%d-%H%M%S')"
          git tag -a "$TAG_NAME" -m "Production deployment of ${{ github.sha }}"
          git push origin "$TAG_NAME"