name: Deploy to prod-gcp

on:
  push:
    branches: [ master ]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  CLUSTER: prod-gcp
  RESOURCE: ./nais/deploy.yaml

jobs:
  build:
    name: Build and push docker conatainer
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    name: Deploy to prod-gcp
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Generate nais variables
        run: |
          cat > .nais/vars.yaml <<EOF
          SITEIMPROVE: ${{ secrets.SITEIMPROVE }}
          AMPLITUDE_100000009: ${{ secrets.AMPLITUDE_100000009 }}
          AMPLITUDE_100000264: ${{ secrets.AMPLITUDE_100000264 }}
          AMPLITUDE_100000243: ${{ secrets.AMPLITUDE_100000243 }}
          AMPLITUDE_100000244: ${{ secrets.AMPLITUDE_100000244 }}
          AMPLITUDE_100002286: ${{ secrets.AMPLITUDE_100002286 }}
          REOPS: ${{ secrets.REOPS }}
          EOF
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/deploy.yaml
          VAR: image=${{ env.IMAGE }}
          VARS: .nais/vars.yaml